version: 2.1
orbs:
  node: circleci/node@1.1.6

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.10 

jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: npx eslint .
            - run: ENV_SILENT=true yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish_tag:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "7d:e5:c7:96:fd:0e:b4:ec:1c:49:8f:ea:37:03:f2:82"
      - run:
          name: "Generate tag"
          command: bash <(curl -Ls https://raw.githubusercontent.com/josemiguelmelo/next-git-version/master/generate.sh) > VERSION
      - run:
          name: "Publish tag"
          command: git tag $(cat VERSION) && git push --tags
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-test
      - publish_tag:
          requires:
            - build-and-test
          
      - deploy:
          requires:
            - publish_tag
