version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
        — image: circleci/node:12.10  
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: npx eslint .
            - run: ENV_SILENT=true yarn test
  publish_tag:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "47:28:4f:85:5f:22:61:00:6b:fd:2c:14:92:f8:90:ce"
      - run:
          name: "Generate tag"
          command: bash <(curl -Ls https://raw.githubusercontent.com/josemiguelmelo/next-git-version/master/generate.sh) > VERSION
      - run:
          name: "Publish tag"
          command: git tag $(cat VERSION) && git push --tags
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-test
      - publish_tag:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
